# Generated by Django 3.0.7 on 2020-07-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion_producto', models.TextField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_nuevaorden', models.IntegerField()),
                ('prod_descontinuado', models.BooleanField()),
                ('dias_espera', models.IntegerField()),
            ],
        ),
    ]
