# Generated by Django 3.0.7 on 2020-07-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='id_producto',
            new_name='id',
        ),
    ]
