# Generated by Django 3.0.7 on 2020-07-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='cant',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.CharField(choices=[('Caja', 'Caja'), ('Bolsa', 'Bolsa'), ('Frasco', 'Frasco')], max_length=200, null=True),
        ),
    ]
