# Generated by Django 3.0.7 on 2020-07-24 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventario', '0002_auto_20200724_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='operation',
            name='cant',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de movimiento'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=100, null=True, verbose_name='Tipo de operación'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Product', verbose_name='ID de producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cant',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.CharField(choices=[('Caja', 'Caja'), ('Bolsa', 'Bolsa'), ('Frasco', 'Frasco')], max_length=200, null=True, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_in',
            field=models.FloatField(null=True, verbose_name='Precio de entrada'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_out',
            field=models.FloatField(null=True, verbose_name='Precio de salida'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='cant',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='cash',
            field=models.FloatField(null=True, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de venta'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Operation', verbose_name='Tipo de operación'),
        ),
    ]
