# Generated by Django 3.0.7 on 2020-07-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_auto_20200727_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=255, null=True, verbose_name='Nombre de la categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['categoria_id'],
            },
        ),
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('id_inv', models.AutoField(primary_key=True, serialize=False)),
                ('cant_disp', models.IntegerField(verbose_name='Cantidada disponible')),
                ('cant_min', models.IntegerField(verbose_name='Cantidad mínima')),
                ('cant_max', models.IntegerField(verbose_name='Cantidad Máxima')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['id_inv'],
            },
        ),
        migrations.CreateModel(
            name='Metodos_envio',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_envio', models.CharField(max_length=255, null=True, verbose_name='Metodo del envio')),
            ],
            options={
                'verbose_name': 'Metodo_envio',
                'verbose_name_plural': 'Metodos_envios',
                'ordering': ['metodo_envio'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50, null=True, verbose_name='Nombre del proveedor')),
                ('nombre_contacto', models.CharField(max_length=50, null=True, verbose_name='Nombre de contacto representante')),
                ('cargo_contacto', models.CharField(max_length=50, null=True, verbose_name='Cargo del contacto')),
                ('direccion', models.CharField(max_length=255, null=True, verbose_name='Direccion del proveedor')),
                ('codigo_postal', models.CharField(max_length=10, null=True, verbose_name='Cosigo postal')),
                ('ciudad', models.CharField(max_length=50, null=True, verbose_name='Ciudad del proveedor')),
                ('pais', models.CharField(max_length=50, null=True, verbose_name='Pais')),
                ('telefono', models.CharField(max_length=12, null=True, verbose_name='Telefono')),
                ('fax', models.CharField(max_length=12, null=True, verbose_name='Fax del proveedor')),
                ('terminos_pago', models.CharField(max_length=255, null=True, verbose_name='Terminos de pago')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo electronico')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_proveedor'],
            },
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['nombre_producto'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion_producto',
            field=models.TextField(null=True, verbose_name='Descripcion del producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='dias_espera',
            field=models.IntegerField(blank=True, verbose_name='Dias para re-abastecer'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nivel_nuevaorden',
            field=models.IntegerField(blank=True, verbose_name='Nivel para generar nueva orden'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre_producto',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_descontinuado',
            field=models.BooleanField(verbose_name='Producto descontinuado'),
        ),
    ]
