# Generated by Django 3.0.7 on 2020-07-24 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventario', '0003_auto_20200724_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de movimiento')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Product', verbose_name='ID de producto')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre de proveedor')),
                ('adrress', models.CharField(max_length=100, null=True, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Numero de telefono')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('cash', models.FloatField(null=True, verbose_name='Precio total')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de venta')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Entry', verbose_name='Tipo de operación')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de vendedor')),
            ],
        ),
        migrations.RemoveField(
            model_name='sell',
            name='operation_type',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
