# Generated by Django 3.0.7 on 2020-07-24 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventario', '0004_auto_20200724_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='operation_type',
        ),
        migrations.AddField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='entry',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Provider', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de vendedor'),
        ),
    ]
