# Generated by Django 3.0.7 on 2020-07-24 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventario', '0005_auto_20200724_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Salida', 'verbose_name_plural': 'Salidas'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cant',
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre del proveedor'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre del cliente'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('name_product', models.CharField(max_length=100, null=True, verbose_name='Producto')),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de entrada')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Entry')),
            ],
        ),
    ]
