# Generated by Django 3.0.7 on 2020-07-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_detalle_compras_historia_mov_locaciones_ordenes_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='categoria',
            field=models.CharField(max_length=255, verbose_name='Nombre de la categoria'),
        ),
    ]
