# Generated by Django 3.0.7 on 2020-07-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_auto_20200724_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='provider',
            field=models.CharField(max_length=200, null=True, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='cant',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cant',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Entry'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cant',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad'),
        ),
    ]
