# Generated by Django 3.0.7 on 2020-07-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_auto_20200727_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='categoria',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre de la categoria'),
        ),
    ]
