# Generated by Django 3.0.7 on 2020-07-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_auto_20200727_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Detalle_compras',
        ),
        migrations.DeleteModel(
            name='Historia_mov',
        ),
        migrations.DeleteModel(
            name='Locaciones',
        ),
        migrations.DeleteModel(
            name='Metodos_envio',
        ),
        migrations.DeleteModel(
            name='Ordenes_compra',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
    ]
