# Generated by Django 3.0.7 on 2020-07-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_auto_20200730_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=255, verbose_name='Nombre de la categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['categoria_id'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('descripcion_producto', models.TextField(null=True, verbose_name='Descripcion del producto')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('nivel_nuevaorden', models.IntegerField(blank=True, verbose_name='Nivel para generar nueva orden')),
                ('prod_descontinuado', models.BooleanField(verbose_name='Producto descontinuado')),
                ('dias_espera', models.IntegerField(blank=True, verbose_name='Dias para re-abastecer')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre_producto'],
            },
        ),
    ]
