# Generated by Django 3.0.7 on 2020-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_auto_20200728_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_in',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_out',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cash',
        ),
        migrations.AddField(
            model_name='inventory',
            name='price_product',
            field=models.PositiveIntegerField(null=True, verbose_name='Precio del producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True, verbose_name='Precio de entrada'),
        ),
        migrations.AddField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(default=None, to='Inventario.Provider', verbose_name='Proveedores'),
        ),
    ]
