# Generated by Django 3.0.7 on 2020-07-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_categorias_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarios',
            name='cant_disp',
            field=models.IntegerField(verbose_name='Cantidad disponible'),
        ),
    ]
