# Generated by Django 3.0.7 on 2020-08-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_auto_20200806_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='provider',
        ),
    ]
