# Generated by Django 3.0.7 on 2020-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0010_auto_20200730_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion_producto',
            field=models.TextField(blank=True, verbose_name='Descripcion del producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_descontinuado',
            field=models.BooleanField(blank=True, verbose_name='Producto descontinuado'),
        ),
    ]
