# Generated by Django 3.0.7 on 2020-07-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0012_auto_20200730_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='dias_espera',
            field=models.IntegerField(null=True, verbose_name='Dias para re-abastecer'),
        ),
    ]
