# Generated by Django 3.0.7 on 2020-07-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0013_auto_20200730_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='dias_espera',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dias para re-abastecer'),
        ),
    ]
