# Generated by Django 3.1 on 2020-08-08 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventario', '0014_auto_20200807_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60, null=True, verbose_name='Nombre del cliente')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Numero de telefono')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo electronico')),
                ('razon_social', models.CharField(max_length=200, null=True, verbose_name='Razon social')),
                ('RUC', models.CharField(max_length=11, null=True, verbose_name='RUC')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=30, null=True, verbose_name='Nombre de la linea')),
                ('have_sub_line', models.BooleanField(default=False, verbose_name='Sublinea')),
            ],
            options={
                'verbose_name': 'Linea',
                'verbose_name_plural': 'Lineas',
            },
        ),
        migrations.CreateModel(
            name='Sub_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_line_name', models.CharField(max_length=30, null=True, verbose_name='Nombre de sublinea')),
            ],
            options={
                'verbose_name': 'Sublinea',
                'verbose_name_plural': 'Sublineas',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='line',
            field=models.CharField(max_length=100, null=True, verbose_name='Linea del producto'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sub_line',
            field=models.CharField(max_length=100, null=True, verbose_name='Sublinea del producto'),
        ),
        migrations.AddField(
            model_name='provider',
            name='RUC',
            field=models.CharField(max_length=11, null=True, verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='provider',
            name='razon_social',
            field=models.CharField(max_length=20, null=True, verbose_name='Razon social'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='product',
            name='line',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Inventario.line'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_line',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Inventario.sub_line'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Inventario.client', verbose_name='Cliente'),
        ),
    ]
