# Generated by Django 3.0.7 on 2020-07-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0014_auto_20200730_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='nivel_nuevaorden',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nivel para generar nueva orden'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_descontinuado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Producto descontinuado'),
        ),
    ]
