# Generated by Django 3.0.7 on 2020-07-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0015_auto_20200730_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='prod_descontinuado',
            field=models.BooleanField(verbose_name='Producto descontinuado'),
        ),
    ]
