# Generated by Django 3.1 on 2020-08-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0015_auto_20200807_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='have_sub_line',
        ),
    ]
