# Generated by Django 3.0.7 on 2020-07-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0016_auto_20200730_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes_compra',
            fields=[
                ('id_orden_compra', models.AutoField(primary_key=True, serialize=False)),
                ('numero_compra', models.CharField(max_length=255, verbose_name='Numero de la compra')),
                ('descripción_compra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion de la compra')),
                ('fecha_orden', models.DateField(verbose_name='Fecha de orden')),
                ('fecha_embarque', models.DateField(verbose_name='Fecha de embarque')),
                ('fecha_requerida', models.DateField(verbose_name='Fecha requerida')),
                ('fecha_promesa', models.DateField(verbose_name='Fecha promesa')),
            ],
            options={
                'verbose_name': 'Orden_compra',
                'verbose_name_plural': 'Ordenes_compra',
                'ordering': ['id_orden_compra'],
            },
        ),
    ]
