# Generated by Django 3.1 on 2020-08-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0017_sale_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50, null=True, verbose_name='Nombre de almacen')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='Ubicacion')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sub_line',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_line',
        ),
        migrations.AddField(
            model_name='inventory',
            name='presentation',
            field=models.CharField(max_length=110, null=True, verbose_name='Presentación'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='providers',
            field=models.CharField(max_length=100, null=True, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.CharField(max_length=50, null=True, verbose_name='Almacen'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Inventario.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Inventario.entry'),
        ),
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Inventario.line'),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.CharField(choices=[('Unidad', 'Unidad'), ('Lata', 'Lata'), ('Paquete', 'Paquete'), ('KIT', 'KIT'), ('Caja', 'Caja'), ('Bolsa', 'Bolsa'), ('Frasco', 'Frasco')], max_length=200, null=True, verbose_name='Presentación'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='providers',
        ),
        migrations.AddField(
            model_name='product',
            name='providers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Inventario.provider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Inventario.client', verbose_name='Cliente'),
        ),
        migrations.DeleteModel(
            name='Sub_line',
        ),
        migrations.AddField(
            model_name='entry',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Inventario.store', verbose_name='Almacen'),
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Inventario.store', verbose_name='Almacen'),
        ),
    ]
