# Generated by Django 3.0.7 on 2020-07-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0017_ordenes_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_compra',
            name='fecha_embarque',
            field=models.DateField(blank=True, verbose_name='Fecha de embarque'),
        ),
        migrations.AlterField(
            model_name='ordenes_compra',
            name='fecha_promesa',
            field=models.DateField(blank=True, verbose_name='Fecha promesa'),
        ),
        migrations.AlterField(
            model_name='ordenes_compra',
            name='fecha_requerida',
            field=models.DateField(blank=True, verbose_name='Fecha requerida'),
        ),
    ]
