# Generated by Django 3.0.7 on 2020-07-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0019_auto_20200730_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locaciones',
            fields=[
                ('id_loc', models.AutoField(primary_key=True, serialize=False)),
                ('cod_loc', models.CharField(max_length=15, verbose_name='Codigo de la localizacion')),
                ('desc_loc', models.CharField(max_length=150, null=True, verbose_name='Descripción de la localizacion')),
                ('isla', models.CharField(max_length=15, null=True, verbose_name='Codigo de isla de almacen')),
                ('seccion', models.CharField(max_length=15, null=True, verbose_name='Codigo de sección')),
                ('nivel', models.CharField(max_length=15, null=True, verbose_name='Codigo de nivel')),
                ('contenedor', models.CharField(max_length=15, null=True, verbose_name='Codigo de contenedor')),
                ('capacidad', models.IntegerField(null=True, verbose_name='Capacidad del contenedor')),
            ],
            options={
                'verbose_name': 'Locacion',
                'verbose_name_plural': 'Locaciones',
                'ordering': ['cod_loc'],
            },
        ),
    ]
