# Generated by Django 3.1 on 2020-08-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0019_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
