# Generated by Django 3.0.7 on 2020-07-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0021_auto_20200730_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['categoria'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
