# Generated by Django 3.0.7 on 2020-07-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0022_auto_20200730_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Categorias'),
        ),
    ]
