# Generated by Django 3.0.7 on 2020-07-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0023_productos_categoria_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarios',
            name='id_producto',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Productos'),
        ),
    ]
