# Generated by Django 3.0.7 on 2020-07-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0024_inventarios_id_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_mov',
            fields=[
                ('id_inv_hist', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mov', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA')], max_length=25, verbose_name='Tipo de movimiento')),
                ('cant_mov', models.IntegerField(verbose_name='Cantidad de movimiento')),
                ('fecha_mov', models.DateField(auto_now=True, verbose_name='Fecha de movimiento')),
                ('hora_mov', models.DateTimeField(auto_now=True, verbose_name='Hora de movimiento')),
                ('lote', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código del lote del producto')),
                ('caducidad', models.DateField(verbose_name='Fecha de caducidad')),
                ('id_loc', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Locaciones')),
                ('id_producto', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Productos')),
            ],
            options={
                'verbose_name': 'Historia_mov',
                'verbose_name_plural': 'Historias_mov',
                'ordering': ['fecha_mov'],
            },
        ),
    ]
