# Generated by Django 3.0.7 on 2020-07-30 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0025_historia_mov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_compras',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_orden', models.IntegerField(verbose_name='Cantidad de orden')),
                ('cantidad_recibida', models.IntegerField(verbose_name='Cantidad recibida')),
            ],
            options={
                'verbose_name': 'Detalle_compra',
                'verbose_name_plural': 'Detalle_compras',
                'ordering': ['id_detalle_compra'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50, verbose_name='Nombre del proveedor')),
                ('nombre_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de contacto representante')),
                ('cargo_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo del contacto')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion del proveedor')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cosigo postal')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad del proveedor')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono')),
                ('fax', models.CharField(blank=True, max_length=12, null=True, verbose_name='Fax del proveedor')),
                ('terminos_pago', models.CharField(blank=True, max_length=255, null=True, verbose_name='Terminos de pago')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electronico')),
                ('notas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_proveedor'],
            },
        ),
        migrations.AddField(
            model_name='ordenes_compra',
            name='metodoenvio_id',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Metodos_envio'),
        ),
        migrations.AddField(
            model_name='ordenes_compra',
            name='proveedor_id',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Proveedores'),
        ),
    ]
