# Generated by Django 3.0.7 on 2020-07-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0026_auto_20200730_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenes_compra',
            options={},
        ),
        migrations.RemoveField(
            model_name='ordenes_compra',
            name='descripción_compra',
        ),
        migrations.RemoveField(
            model_name='ordenes_compra',
            name='fecha_embarque',
        ),
        migrations.RemoveField(
            model_name='ordenes_compra',
            name='fecha_orden',
        ),
        migrations.RemoveField(
            model_name='ordenes_compra',
            name='fecha_promesa',
        ),
        migrations.RemoveField(
            model_name='ordenes_compra',
            name='fecha_requerida',
        ),
        migrations.RemoveField(
            model_name='ordenes_compra',
            name='metodoenvio_id',
        ),
        migrations.RemoveField(
            model_name='ordenes_compra',
            name='numero_compra',
        ),
        migrations.RemoveField(
            model_name='ordenes_compra',
            name='proveedor_id',
        ),
    ]
