# Generated by Django 3.0.7 on 2020-07-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0027_auto_20200730_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_compras',
            name='cantidad_orden',
        ),
        migrations.RemoveField(
            model_name='detalle_compras',
            name='cantidad_recibida',
        ),
    ]
