# Generated by Django 3.0.7 on 2020-07-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0028_auto_20200730_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_compras',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
