# Generated by Django 3.0.7 on 2020-07-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0029_auto_20200730_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedores',
            options={'ordering': ['nombre_proveedor'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
