# Generated by Django 3.0.7 on 2020-07-30 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0030_auto_20200730_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenes_compra',
            options={'ordering': ['id_orden_compra'], 'verbose_name': 'Orden_compra', 'verbose_name_plural': 'Ordenes_compra'},
        ),
    ]
