# Generated by Django 3.0.7 on 2020-07-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0031_auto_20200730_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_compras',
            options={'ordering': ['id_detalle_compra'], 'verbose_name': 'Detalle_compra', 'verbose_name_plural': 'Detalle_compras'},
        ),
        migrations.AddField(
            model_name='ordenes_compra',
            name='descripción_compra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion de la compra'),
        ),
    ]
