# Generated by Django 3.0.7 on 2020-07-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0034_auto_20200730_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compras',
            name='ordencompra_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Ordenes_compra'),
        ),
        migrations.AddField(
            model_name='detalle_compras',
            name='producto_id',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Productos'),
        ),
    ]
