# Generated by Django 3.0.7 on 2020-07-30 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0035_auto_20200730_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes_compra',
            name='metodoenvio_id',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Metodos_envio'),
        ),
        migrations.AddField(
            model_name='ordenes_compra',
            name='proveedor_id',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Proveedores'),
        ),
    ]
